name: Deploy application

on:
  push:
    branches: [ next ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ViteJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/jonathan/reverse-proxy/code/league-pepite
            git reset --hard
            git pull origin next
            cd /home/jonathan/reverse-proxy
            docker-compose stop leaguepepite
            docker-compose rm -f leaguepepite
            docker-compose up -d leaguepepite
