name: Deploy application
 
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ViteJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/reverse-proxy/code/league-pepite
            git pull
            cd /root/reverse-proxy
            docker-compose up -d --force-recreate --no-deps --build leaguepepite
